#!/bin/bash
#
# ./main_mo con01
# mv fs_copy con01

for i in {01..17};
  do echo "con$i";
  ./main_mo "con$i"
  mv fs_copy "con$i"
done

for i in {01..15};
  do echo "cat$i";
  ./main_mo "cat$i"
  mv fs_copy "cat$i"
done
