#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=120gb,walltime=24:00:00
#PBS -N pRF
#PBS -V
SUBNAME=$1
set -e
set -x

freesurfer_dir=$(jq -r .freesurfer config.json)
[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

 subjects_dir=/home/mohamed/Desktop/fs_output

# time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://davhunt/neuropythy:1.5 python -m neuropythy benson14_retinotopy -d $subjects_dir con01
time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/$SUBNAME
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/con02
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/con03
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/con04
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/con05
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/con06
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/con07
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/con08
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/con09
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/con10
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/con11
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/con12
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/con13
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/con14
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/con15
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/con16
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/con17
#
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/cat01
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/cat02
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/cat03
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/cat04
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/cat05
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/cat06
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/cat07
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/cat08
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/cat09
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/cat10
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/cat11
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/cat12
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/cat13
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/cat14
# time singularity exec -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/neuropythy:1.5 ./run.sh $subjects_dir/cat15
